### ISSUE TITLE
Demo (and instructions) do not show how to select variables

### ISSUE THREAD

**Issue by Fmstrat** [Telerik-Verified-Plugins/SQLite-DemoApp#1]
The demo app, as well as the instructions on http://plugins.cordova.io/#/package/com.triarc.sqliteplugin do not have any examples of how to get a value from a select statement. They only show how to get row counts. It would be very helpful if one or both of these demonstrated standard querying. Thanks.

**Comment by EddyVerbruggen** [comment]
Hi, point taken. The demo app has been updated as well as the examples in the [Marketplace doc](http://plugins.telerik.com/plugin/sqlite).

I hope this suits your needs,
Eddy
