### ISSUE TITLE
Sample doesn't work on WP.

### ISSUE THREAD

**Issue by zbranzov** [Telerik-Verified-Plugins/SQLite-DemoApp#2]
Hi Eddy,

I cloned the sample app in AppBuilder Windows client and deployed it on WP 8 and 8.1 device but the Cordova deviceready event doesn't get fired.
If I remove the plugin from the Plugins folder and add it from the Manage packages feature it works.
Would you take a look what could cause this strange behavior?

Thanks,
Zdravko

**Comment by EddyVerbruggen** [comment]
Hi Zdravko,

Well spotted.. there was a `test-www` folder in the SQLite plugin repo which seemed to prevent the app to run correctly on WP8. I removed the folder and it's OK now. There must have been a file in there which did crazy things with AppBuilder, but only on the WP platform. Perhaps it's something you want to further investigate, but I'll make sure that folder won't come back ;)

Demo app updated, as well as the plugin itself.

Best,
Eddy
